// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9Zoj1IoTQ0XE3IXAYJ0vXAh8-ho2l7A',
    appId: '1:1009432603344:web:07eb28226bfe36b35a8cd5',
    messagingSenderId: '1009432603344',
    projectId: 'fooddeliveryapp-2d863',
    authDomain: 'fooddeliveryapp-2d863.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-2d863.appspot.com',
    measurementId: 'G-4JDG8PWDZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVaqjKw_h_pyos-NOTB0IhoTu1n1xuUoE',
    appId: '1:1009432603344:android:0c7f89ad55267fe35a8cd5',
    messagingSenderId: '1009432603344',
    projectId: 'fooddeliveryapp-2d863',
    storageBucket: 'fooddeliveryapp-2d863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ8wIwr-oqJ2C6DUw5dwt8GrlICYvEuFM',
    appId: '1:1009432603344:ios:e50ff05540c0425a5a8cd5',
    messagingSenderId: '1009432603344',
    projectId: 'fooddeliveryapp-2d863',
    storageBucket: 'fooddeliveryapp-2d863.appspot.com',
    iosBundleId: 'com.example.trungdevTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ8wIwr-oqJ2C6DUw5dwt8GrlICYvEuFM',
    appId: '1:1009432603344:ios:e50ff05540c0425a5a8cd5',
    messagingSenderId: '1009432603344',
    projectId: 'fooddeliveryapp-2d863',
    storageBucket: 'fooddeliveryapp-2d863.appspot.com',
    iosBundleId: 'com.example.trungdevTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo9Zoj1IoTQ0XE3IXAYJ0vXAh8-ho2l7A',
    appId: '1:1009432603344:web:f59f99a8d09bb4395a8cd5',
    messagingSenderId: '1009432603344',
    projectId: 'fooddeliveryapp-2d863',
    authDomain: 'fooddeliveryapp-2d863.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-2d863.appspot.com',
    measurementId: 'G-J20E1LSVCW',
  );
}
